version: '3.1'

volumes:
    mongo_data:
        name: ${VOLUME_ID}
        
services: 
    mongo: 
        image: mongo:4.4.1-bionic
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: test
            MONGO_INITDB_ROOT_PASSWORD: test
        ports:
            - 2717:27017
        volumes: 
            - mongo_data:/data/db
    
    mongo-express:
        image: mongo-express:0.54.0
        restart: always
        ports: 
            - 8081:8081
        environment: 
            ME_CONFIG_MONGODB_ADMINUSERNAME: test
            ME_CONFIG_MONGODB_ADMINPASSWORD: test
